### ISSUE TITLE
Custom vector.toml.tmpl ?

### ISSUE THREAD

**Issue by dani** [mr-karan/nomad-vector-logger#6]
Hi.
First, let me thank you for this tool : it's exactly what I was looking for to collect my Nomad logs and send them to Loki with Vector (I was scrapping all logs in my alloc, and using the name of the file to identify the task, but was missing a clean way to get the job, group etc.)
I'd like to know if it's possible to use a custom vector.toml.tmpl file, I tried puting it in the working dir, but with no effect. Is the only way to rebuild from source ?

Regards, Daniel

**Comment by mr-karan** [comment]
Hey! 

Thanks, glad you find it useful.

Yes it's possible to mount a custom vector file. This binary only templates out `nomad.toml` which is basically an incomplete pipeline for vector. Further transformation/sink config can be added as a separate file since vector supports reading multiple `.toml` files. Here's a quick example:

```
job "vector" {
  datacenters = ["dc1"]
  namespace   = "logging"
  type        = "system"

  group "vector" {
    count = 1
    restart {
      attempts = 3
      interval = "10m"
      delay    = "30s"
      mode     = "fail"
    }

    network {
      port "metrics" {
        to     = 8686
        static = 8686
      }
      mode = "host"
    }

    task "vector" {
      # Need access to the underlying `/opt/nomad/data/alloc` directory to get the logs.
      driver = "raw_exec"

      # Run the program.
      config {
        command = "$${NOMAD_TASK_DIR}/vector-x86_64-unknown-linux-gnu/bin/vector"
        args = [
          "--watch-config",
          "--config",
          "$${NOMAD_TASK_DIR}/base.toml",
          "--config-dir=$${NOMAD_ALLOC_DIR}/vector_gen_configs/"
        ]
      }

      # Template with Vector's configuration
      template {
        data        = file(abspath("./base.tpl.toml"))
        destination = "local/base.toml"
        change_mode = "restart"
      }

      kill_timeout = "60s"
    }

    task "nomad-vector-logger" {
      # Need access to Nomad API running on 0.0.0.0
      driver = "raw_exec"

      lifecycle {
        hook    = "prestart"
        sidecar = true
      }

      # Run the program.
      config {
        command = "$${NOMAD_TASK_DIR}/nomad-vector-logger.bin"
        args = [
          "--config",
          "$${NOMAD_TASK_DIR}/nomad-vector-logger.toml"
        ]
      }

      # config for program
      template {
        data        = file(abspath("./nomad-vector-logger.toml"))
        destination = "local/nomad-vector-logger.toml"
        change_mode = "restart"
      }

      # Mount as many custom config as you want
      template {
        data        = file(abspath("./static/sink.tpl.toml"))
        destination = "local/static/sink.toml"
        change_mode = "restart"
        # overriding the delimiters to [[ ]] to avoid conflicts with Vector's native templating, which also uses {{ }}
        left_delimiter  = "[["
        right_delimiter = "]]"
      }
    }

    task "await-config-generation" {
      driver = "raw_exec"

      # This waits for 30s so that the files are generated.
      config {
        command = "/usr/bin/bash"
        args = [
          "-c",
          "echo -n 'Waiting for nomad.toml to be generated by nomad-vector-logger'; sleep 30"
        ]
      }

      lifecycle {
        hook    = "prestart"
        sidecar = false
      }
    }
  }
}
```


You may need to tweak a lot of things here, but this should help you achieve what you want.

**Comment by dani** [comment]
Thanks. I've looked at the sample Nomad job. I understand I can add further Vector pipelines, but still can't see how to use a custom [vector.toml.tmpl](https://github.com/mr-karan/nomad-vector-logger/blob/main/vector.toml.tmpl) in order to customize the generated nomad.toml file. For example, I'd like to ignore some of the tasks (I use a lot of sidecars to expose metrics with mTLS auth, and I'm not really interested in the logs from those sidecars)

**Comment by dani** [comment]
Ah, forget about it. I'm a bit confused : putting a custom nomad.toml file in the extra_templates_dir is the only things needed. I'll try to wotk with this and report back if I have any further question :-)
