### ISSUE TITLE
More efficient file watcher

### ISSUE THREAD

**Issue by baodrate** [mr-karan/nomad-vector-logger#8]
In [your blog](https://mrkaran.dev/posts/nomad-logging/), you mentioned your method of watching the csv file for changes: https://github.com/mr-karan/nomad-vector-logger/blob/csv/examples/deployment.nomad?ref=karan-sharma#L124-L151

This might be doubling down on a hacky approach, but maybe consider [`entr`](https://eradman.com/entrproject/)? ([github repo](https://github.com/eradman/entr)). It would reduce your script down to:

```sh
#!/usr/bin/env bash
entr -n pkill -f -SIGHUP vector <<<$1
```

**Comment by baodrate** [comment]
Nevermind, I hadn't finished reading the post and didn't realize you've already moved on from that approach 😅

**Comment by mr-karan** [comment]
Thanks @qubidt TIL about `entr`. Quite a cool hack :)
